### PR TITLE
Update q-1.cpp

### LINKED ISSUE #1: WAP to find area of a circle, a rectangle and a triangle, using concept of function overloading.

### PR DESCRIPTION
**Pull request by neha0123**

### CODE REVIEW

**Comment by neha0123** [comment]
please review it

**Review by SahilKr24 — APPROVED** [review]
Approved.

**Comment by neha0123** [comment]
Can u assign it as hactoberfest accepted

**Comment by SahilKr24** [comment]
Merging it will count against one of the four PRs. :)

**Pull request merged**
